export const Colors = {
  background:      '#0D0D0D',
  surface:         '#1A1A1A',
  surfaceRaised:   '#242424',
  border:          '#2E2E2E',
  textPrimary:     '#F0F0F0',
  textSecondary:   '#8A8A8A',
  textDisabled:    '#444444',
  accent:          '#4A9B6E',
  accentMuted:     '#16301F',
  accentText:      '#6FBF95',
  stateRipe:       '#4ADE80',
  stateWarning:    '#FACC15',
  stateOverripe:   '#F97316',
  stateUnripe:     '#60A5FA',
  stateAlmostReady:'#FACC15',
  stateUseSoon:    '#F97316',
  stateRaw:        '#F87171',
  stateRare:       '#FB923C',
  stateMediumRare: '#FCD34D',
  stateMedium:     '#A3E635',
  stateWellDone:   '#4ADE80',
  stateError:      '#F87171',

  // Match-tier verdict colors (currently only SelfieCheckResultCard) — always
  // paired with icons, never used alone.
  matchTierStrong:     '#4ADE80',
  matchTierGood:       '#86EFAC',
  matchTierNeutral:    '#94A3B8',
  matchTierMildClash:  '#FACC15',
  matchTierStrongClash:'#F87171',
} as const;
